// Retell tool definitions used when configuring agents/LLMs
const buildClinicTools = ({ baseUrl, secret }) => ([
  {
    type: "custom",
    name: "get_patient_by_phone",
    description: "Find existing patient by phone number",
    url: `${baseUrl}/retell/functions/get_patient_by_phone`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: true,
    execution_message_description: "Let me check your record.",
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["clinic_id", "caller_phone"],
      properties: {
        clinic_id: { type: "string" },
        caller_phone: { type: "string", description: "E.164 or raw, we'll normalize" },
      },
    },
  },
  {
    type: "custom",
    name: "find_slots",
    description: "Get next available appointment slots",
    url: `${baseUrl}/retell/functions/find_slots`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: false,
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["clinic_id", "service", "window_start", "window_end"],
      properties: {
        clinic_id: { type: "string" },
        service: { type: "string" },
        window_start: { type: "string", description: "ISO start" },
        window_end: { type: "string", description: "ISO end" },
      },
    },
  },
  {
    type: "custom",
    name: "create_appointment",
    description: "Book an appointment in Supabase",
    url: `${baseUrl}/retell/functions/create_appointment`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: true,
    execution_message_description: "I'm creating your appointment.",
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["clinic_id", "service", "patient", "slot"],
      properties: {
        clinic_id: { type: "string" },
        service: { type: "string" },
        patient: {
          type: "object",
          required: ["full_name", "phone"],
          properties: {
            full_name: { type: "string" },
            phone: { type: "string" },
            dob: { type: "string", description: "YYYY-MM-DD", nullable: true },
          },
        },
        slot: {
          type: "object",
          required: ["start"],
          properties: {
            start: { type: "string", description: "ISO start" },
            end: { type: "string", description: "ISO end", nullable: true },
          },
        },
        notes: { type: "string", nullable: true },
      },
    },
  },
  {
    type: "custom",
    name: "get_services",
    description: "Fetch list of services and add-ons",
    url: `${baseUrl}/retell/functions/get_services`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: false,
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["clinic_id"],
      properties: { clinic_id: { type: "string" } },
    },
  },
  { type: "end_call", name: "end_call", description: "End the call with the user." },
]);

const buildRestaurantTools = ({ baseUrl, secret }) => ([
  {
    type: "custom",
    name: "get_customer_by_phone",
    description: "Find existing restaurant customer by phone number",
    url: `${baseUrl}/retell/functions/get_customer_by_phone`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: true,
    execution_message_description: "Let me check our guest list.",
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["restaurant_id"],
      properties: {
        restaurant_id: { type: "string" },
        caller_phone: {
          type: "string",
          description: "Caller number (raw or E.164); optional if caller ID is available",
        },
      },
    },
  },
  {
    type: "custom",
    name: "get_menu",
    description: "Fetch current menu with categories and prices",
    url: `${baseUrl}/retell/functions/get_menu`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: false,
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["restaurant_id"],
      properties: { restaurant_id: { type: "string" } },
    },
  },
  {
    type: "custom",
    name: "check_table_availability",
    description: "Check if a reservation slot is open",
    url: `${baseUrl}/retell/functions/check_table_availability`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: true,
    execution_message_description: "Let me verify availability.",
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["restaurant_id", "reservation_time", "party_size"],
      properties: {
        restaurant_id: { type: "string" },
        reservation_time: { type: "string", description: "ISO start" },
        party_size: { type: "integer", minimum: 1 },
        duration_minutes: { type: "integer" },
      },
    },
  },
  {
    type: "custom",
    name: "create_reservation",
    description: "Create a table reservation",
    url: `${baseUrl}/retell/functions/create_reservation`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: true,
    execution_message_description: "I'll secure that table for you.",
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["restaurant_id", "reservation_time", "guest", "party_size"],
      properties: {
        restaurant_id: { type: "string" },
        reservation_time: { type: "string", description: "ISO start" },
        party_size: { type: "integer", minimum: 1 },
        duration_minutes: { type: "integer" },
        special_requests: { type: "string", nullable: true },
        guest: {
          type: "object",
          required: ["full_name", "phone"],
          properties: {
            full_name: { type: "string" },
            phone: { type: "string" },
            email: { type: "string", nullable: true },
          },
        },
      },
    },
  },
  {
    type: "custom",
    name: "place_order",
    description: "Create a pickup or delivery order (caller phone optional for inbound calls)",
    url: `${baseUrl}/retell/functions/place_order`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: true,
    execution_message_description: "Adding that order for you.",
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["restaurant_id", "items", "customer"],
      properties: {
        restaurant_id: { type: "string" },
        items: {
          type: "array",
          minItems: 1,
          items: {
            type: "object",
            required: ["menu_item_id", "name", "quantity", "price"],
            properties: {
              menu_item_id: { type: "string" },
              name: { type: "string" },
              quantity: { type: "integer", minimum: 1 },
              price: { type: "number" },
              notes: { type: "string", nullable: true },
            },
          },
        },
        customer: {
          type: "object",
          required: ["full_name"],
          properties: {
            full_name: { type: "string" },
            phone: { type: "string" },
            email: { type: "string", nullable: true },
          },
        },
        delivery_or_pickup: { type: "string", enum: ["pickup", "delivery"] },
        delivery_address: { type: "string", nullable: true },
        total_amount: { type: "number" },
      },
    },
  },
  {
    type: "custom",
    name: "get_order_status",
    description: "Lookup an order by id or phone",
    url: `${baseUrl}/retell/functions/get_order_status`,
    method: "POST",
    parameter_type: "json",
    args_at_root: false,
    headers: { "x-retell-secret": secret },
    speak_during_execution: false,
    speak_after_execution: true,
    timeout_ms: 120000,
    parameters: {
      type: "object",
      required: ["restaurant_id"],
      properties: {
        restaurant_id: { type: "string" },
        order_id: { type: "string" },
        customer_phone: { type: "string" },
      },
    },
  },
  { type: "end_call", name: "end_call", description: "End the call with the user." },
]);

export const buildRetellTools = ({ baseUrl, secret, orgType = "Clinic" }) =>
  orgType === "Restaurant"
    ? buildRestaurantTools({ baseUrl, secret })
    : buildClinicTools({ baseUrl, secret });
